s=input()
if(s=='V'):
    print("Violet")
elif(s=='I'):
    print("Indigo")
elif(s=='B'):
    print("Blue")
elif(s=='G'):
    print("Green")
elif(s=='Y'):
    print("Yellow")
elif(s=='O'):
    print("Orange")
elif(s=='R'):
    print("Red")
else:
    print("-1")
